<!DOCTYPE html><html lang="en-us" >

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.8.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Han Hao">

  
  
  
    
  
  <meta name="description" content="An example of item response modeling with the mirt package.">

  
  <link rel="alternate" hreflang="en-us" href="https://hanhao23.github.io/project/irttutorial/">

  


  
  
  
  <meta name="theme-color" content="rgb(251, 191, 183)">
  

  
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha256-4w9DunooKSr3MFXHXWyFER38WmPdm361bQS/2KUWZbU=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" integrity="sha256-Vzbj7sDDS/woiFS3uNKo8eIuni59rjyNGtXfstRzStA=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.css" integrity="sha256-SHMGCYmST46SoyGgo4YR/9AlK1vf3ff84Aq9yK4hdqM=" crossorigin="anonymous">
    

    

    
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
    
      

      
      

      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" integrity="sha256-Md1qLToewPeKjfAHU1zyPwOutccPAm5tahnaw7Osw0A=" crossorigin="anonymous" async></script>
      
    
      

      
      

      
    
      

      
      

      
    
      

      
      
        
      

      
    
      

      
      

      
    

  

  
  
  
    
      
      
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cutive+Mono%7CLora:400,700%7CRoboto:400,700&display=swap">
    
  

  
  
  
  
  <link rel="stylesheet" href="/css/academic.css">

  




  


  
  

  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/images/icon_huceea97a4f51140770cf91e986cd49757_5625_32x32_fill_lanczos_center_3.png">
  <link rel="apple-touch-icon" type="image/png" href="/images/icon_huceea97a4f51140770cf91e986cd49757_5625_192x192_fill_lanczos_center_3.png">

  <link rel="canonical" href="https://hanhao23.github.io/project/irttutorial/">

  
  
  
  
  
  
  
    
  
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@HanHao23">
  <meta property="twitter:creator" content="@HanHao23">
  
  <meta property="og:site_name" content="Han Hao Cog Psych">
  <meta property="og:url" content="https://hanhao23.github.io/project/irttutorial/">
  <meta property="og:title" content="Intro to Item Response Modeling in R | Han Hao Cog Psych">
  <meta property="og:description" content="An example of item response modeling with the mirt package."><meta property="og:image" content="https://hanhao23.github.io/project/irttutorial/featured.jpg">
  <meta property="twitter:image" content="https://hanhao23.github.io/project/irttutorial/featured.jpg"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2022-05-12T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2022-05-12T00:00:00&#43;00:00">
  

  


    









<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://hanhao23.github.io/project/irttutorial/"
  },
  "headline": "Intro to Item Response Modeling in R",
  
  "image": [
    "https://hanhao23.github.io/project/irttutorial/featured.jpg"
  ],
  
  "datePublished": "2022-05-12T00:00:00Z",
  "dateModified": "2022-05-12T00:00:00Z",
  
  "author": {
    "@type": "Person",
    "name": "Han Hao"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "Han Hao Cog Psych",
    "logo": {
      "@type": "ImageObject",
      "url": "https://hanhao23.github.io/images/icon_huceea97a4f51140770cf91e986cd49757_5625_192x192_fill_lanczos_center_3.png"
    }
  },
  "description": "An example of item response modeling with the mirt package."
}
</script>

  

  


  


  





  <title>Intro to Item Response Modeling in R | Han Hao Cog Psych</title>

</head>
<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  









<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">Han Hao Cog Psych</a>
    </div>
    

    
    <button type="button" class="navbar-toggler" data-toggle="collapse"
            data-target="#navbar-content" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span><i class="fas fa-bars"></i></span>
    </button>
    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">Han Hao Cog Psych</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-start" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#publications"><span>Publications</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#talks"><span>Talks & Posters</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#projects"><span>Projects</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#contact"><span>Contact</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/files/HanHao_CV.pdf"><span>Download My CV</span></a>
        </li>

        
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">
      
      <li class="nav-item">
        <a class="nav-link js-search" href="#" aria-label="Search"><i class="fas fa-search" aria-hidden="true"></i></a>
      </li>
      

      
      <li class="nav-item dropdown theme-dropdown">
        <a href="#" class="nav-link js-theme-selector" data-toggle="dropdown" aria-haspopup="true">
          <i class="fas fa-palette" aria-hidden="true"></i>
        </a>
        <div class="dropdown-menu">
          <a href="#" class="dropdown-item js-set-theme-light">
            <span>Light</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-dark">
            <span>Dark</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-auto">
            <span>Automatic</span>
          </a>
        </div>
      </li>
      

      

    </ul>

  </div>
</nav>


  <article class="article article-project">

  




















  
  
    
  


<div class="article-container pt-3">
  <h1>Intro to Item Response Modeling in R</h1>

  
  <p class="page-subtitle">An Tutorial on MIRT Package</p>
  

  


<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
    
    May 12, 2022
  </span>
  

  

  

  
  
  

  
  

</div>

  














</div>


<div class="article-header article-container featured-image-wrapper mt-4 mb-4" style="max-width: 720px; max-height: 540px;">
  <div style="position: relative">
    <img src="/project/irttutorial/featured_hu0a1c82d7e435df9f945aab067732232e_2212751_720x0_resize_q90_lanczos.jpg" alt="" class="featured-image">
    
  </div>
</div>



  <div class="article-container">

    <div class="article-style">
      


<div id="overview" class="section level1">
<h1>Overview</h1>
<p>The goal of this document is to introduce applications of R for item response theory (IRT) modeling. Specifically, this document is focused on introducing basic IRT analyses for beginners using the <a href="https://cran.r-project.org/web/packages/mirt/mirt.pdf">“mirt” package</a> (Chalmers, 2012). It is not intended to be a full introduction to data analysis in R, nor to basic mathematics of item response theory. Instead, this tutorial will introduce the key concepts of IRT and important features of corresponding R packages/functions that facilitate IRT modeling for beginners. For a quick reference on the basics of IRT, please see the last section of recommended readings.</p>
<p>In this tutorial, we will focus on unidimensional IRT models by presenting brief R examples using “mirt”. Specifically, we will talk about:<br />
1. Key concepts in IRT;<br />
2. Dichotomous, 1PL Model (Rasch Model);<br />
3. Dichotomous, 2PL Model;<br />
4. Polytomous, Generalized Partial Credit Model.</p>
<div id="install-and-load-packages" class="section level2">
<h2>Install and Load Packages</h2>
<p>The first step is to make sure you have the R packages needed in this tutorial. We can obtain the “mirt” package from CRAN (using “install.packages(‘mirt’)”), or install the development version of the package from Github using the following codes:</p>
<pre class="r"><code>install.packages(&#39;devtools&#39;)
library(&#39;devtools&#39;)
install_github(&#39;philchalmers/mirt&#39;)</code></pre>
<p>We need the following packages in this tutorial:</p>
<pre class="r"><code>library(tidyverse) # For data wrangling and basic visualizations
library(psych) # For descriptive stats and assumption checks
library(mirt) # IRT modeling</code></pre>
</div>
<div id="prepare-the-data" class="section level2">
<h2>Prepare the Data</h2>
<p>The next step is to read in and prepare corresponding data files for the tutorial. The two data files we are using in this tutorial are available at here: <a href="https://hanhao23.github.io/files/WMI_Read_Han_Wide.csv">ReadingSpan</a> and <a href="https://hanhao23.github.io/files/WMI_Rot_Han_Wide.csv">RotationSpan</a>.</p>
<p>These two datasets consist of item-level responses from 261 subjects on 2 complex span tasks: reading span and rotation span. In a complex span task, each item has a varying number of elements to process and memorize (item size). The responses in the two datasets are integer numbers that reflect the numbers of correctly recalled elements for each item. For the reading span task, there are 15 items presented across 3 blocks, with item sizes varied from 3 to 7. For the rotation span task, there are 12 items presented across 3 blocks, with item sizes varied from 2 to 5.</p>
<pre class="r"><code># Conway et al. (2019) Data
wmir &lt;- read.csv(&quot;WMI_Read_Han_wide.csv&quot;)[,-1]
wmirot &lt;- read.csv(&quot;WMI_Rot_Han_wide.csv&quot;)[,-1]

colnames(wmir) &lt;- c(&quot;Subject&quot;, 
                   &quot;V1.3&quot;, &quot;V1.4&quot;,&quot;V1.5&quot;, &quot;V1.6&quot;, &quot;V1.7&quot;,
                   &quot;V2.3&quot;, &quot;V2.4&quot;,&quot;V2.5&quot;, &quot;V2.6&quot;, &quot;V2.7&quot;,
                   &quot;V3.3&quot;, &quot;V3.4&quot;,&quot;V3.5&quot;, &quot;V3.6&quot;, &quot;V3.7&quot;)

colnames(wmirot) &lt;- c(&quot;Subject&quot;, 
                   &quot;S1.2&quot;,&quot;S1.3&quot;, &quot;S1.4&quot;,&quot;S1.5&quot;, 
                   &quot;S2.2&quot;,&quot;S2.3&quot;, &quot;S2.4&quot;,&quot;S2.5&quot;, 
                   &quot;S3.2&quot;,&quot;S3.3&quot;, &quot;S3.4&quot;,&quot;S3.5&quot;)


# Wmi is the full dataset (N = 261)
wmi &lt;- merge(wmir, wmirot, by = &quot;Subject&quot;)

head(wmir)</code></pre>
<pre><code>##   Subject V1.3 V1.4 V1.5 V1.6 V1.7 V2.3 V2.4 V2.5 V2.6 V2.7 V3.3 V3.4 V3.5 V3.6
## 1       1    3    4    5    2    3    3    4    2    2    1    1    2    4    0
## 2       2    3    2    5    6    6    3    3    3    4    7    3    3    5    6
## 3       3    3    4    3    6    6    3    4    5    3    4    3    4    5    5
## 4       4    2    2    2    2    3    3    2    2    0    0    3    4    5    2
## 5       5    3    3    3    4    7    3    4    5    6    5    3    1    5    6
## 6       6    3    4    4    6    2    3    4    5    6    2    3    4    4    6
##   V3.7
## 1    3
## 2    7
## 3    2
## 4    1
## 5    7
## 6    7</code></pre>
<pre class="r"><code>head(wmirot)</code></pre>
<pre><code>##   Subject S1.2 S1.3 S1.4 S1.5 S2.2 S2.3 S2.4 S2.5 S3.2 S3.3 S3.4 S3.5
## 1       1    2    1    0    0    0    3    1    0    1    1    0    0
## 2       2    2    2    1    1    2    3    2    2    2    2    1    1
## 3       3    2    1    4    1    2    3    4    1    1    2    0    3
## 4       4    2    2    3    1    2    0    1    1    2    2    3    4
## 5       5    2    3    4    5    2    3    4    4    2    3    4    2
## 6       7    2    3    0    2    2    3    4    3    2    1    2    1</code></pre>
<p>Labels of the variables in the datasets indicate the corresponding block and item size of a specific item. For example, in the reading span dataset (wmir), the 5th column (“V1.6”) presents subjects’ responses on the item with 6 elements in the 1st block. Subject 1 recalled 2 of the 6 elements correctly.</p>
<p>For a detail summary of the two complex span tasks, see <a href="https://doi.org/10.3758/BF03196772">Conway et al. (2005)</a> and <a href="https://doi.org/10.3758/s13421-021-01242-6">Hao &amp; Conway (2021)</a>.</p>
</div>
</div>
<div id="key-concepts-in-item-response-theory" class="section level1">
<h1>Key Concepts in Item Response Theory</h1>
<p>In this section we will briefly go over some key concepts and terms we will be using in this IRT tutorial.</p>
<p><strong>Scale</strong>: In this tutorial, a scale refers to any quantitative system that is designed to reflect an individual’s standing or level of ability on a latent construct or latent trait. A scale consists of multiple manifest items. These items can be questions in a survey, problems in a test, or trials in an experiment.<br />
- <strong>Dichotomous IRT models</strong> are applied to the items with two possible response categories (yes/no, correct/incorrect, etc.)<br />
- <strong>Polytomous IRT models</strong> are applicable if the items have more than two possible response categories (Likert-type response scale, questions with partial credits, etc.)</p>
<p><strong>Dimensionality</strong>: The number of distinguishable attributes that a scale reflect.<br />
- For <strong>unidimensional IRT models</strong>, it is assumed that the scale only reflect one dimension, such that all items in the scale are assumed to reflect a unitary latent trait.<br />
- For <strong>multidimensional IRT models</strong>, multiple dimensions can be reflected and estimated, such that the responses to the items in the scales are assumed to reflect properties of multiple latent traits.</p>
<p><strong>Theta</strong> (<span class="math inline">\(\Theta\)</span>): the latent construct or trait that is measured by the scale. It represents individual differences on the latent construct being measured.</p>
<p><strong>Information</strong>: an index to characterize the precision of measurement of the item or the test on the underlying latent construct, with high information denoting more precision. In IRT, this index is represented as a function of persons at different levels, such that the information function reflects the range of trait level over which this item or this test is most useful for distinguishing among individuals.</p>
<p><strong>Item Characteristic Curve</strong> (ICC): AKA item trace curve. ICC represents an item response function that models the relationship between a person’s probability for endorsing an item category (<em>p</em>) and the level on the construct measured by the scale (<span class="math inline">\(\Theta\)</span>). For this purpose, the slope of the item characteristic curve is used to assess whether a specific item mean score has either a steeper curve (i.e., high value) or whether the item has a wider curve (i.e., low value) and, therefore, cannot adequately differentiate based on ability level.</p>
<p><strong>Item Difficulty Parameter</strong> (<em>b</em>): the trait level on the latent scale where a person has a 50% chance of responding positively to the item. This definition of item difficulty applies to dichotomous models. For polytomous models, multiple threshold parameters (<em>d</em>s) are estimated for an item so that the latent trait difference between and beyond the response categories are accounted for.<br />
- Conceptually, the role of item difficulty parameters in an IRT model is equivalent to the intercepts of manifests in a latent factor model.</p>
<p><strong>Item Discrimination Parameter</strong> (<em>a</em>): how accurately a given item can differentiate individuals based on ability level. describes the strength of an item’s discrimination between people with trait levels below and above the threshold <em>b</em>. This parameter is also interpreted as describing how an item is related to the latent trait measured by the scale. In other words, the <em>a</em> parameter for an item reflects the magnitude of item reliability (how much the item is contributing to total score variance).<br />
- Conceptually, the role of item discrimination parameters in an IRT model is equivalent to the factor loadings of manifests in a latent factor model.</p>
<p>The “mirt” package includes an interactive graphical interface (shiny app) to allow the parameters to be modified in an IRT exemplar item in real time. To facilitate understanding of these key concepts, you can run the line of code below in your R console to activate an interactive shiny app with examplar item trace plots for different types of IRT models.</p>
<pre class="r"><code>itemplot(shiny = TRUE)</code></pre>
</div>
<div id="unidimensional-dichotomous-irt-models" class="section level1">
<h1>Unidimensional Dichotomous IRT Models</h1>
<p>In this section we will start with the basic unidimensional dichotomous model, in which all items are assumed to measure one latent trait, and the responses to items are all binary (0 = incorrect/no, 1 = correct/yes). We will use the rotation span dataset (wmirot) in this section. As aforementioned, the raw data present numbers of correctly recalled elements for each item, which are not binary responses. Thus, we need to re-score these items using a all-or-nothing unit scoring approach (Conway et al., 2005; p.775), such that only a response with all elements in the item correctly recalled is scored as “correct” (1), while all other responses are scored as “incorrect” (0). The “mirt” package has a built-in function,“key2binary”, to assign binary scores to items in a dataset based on a given answer key. Thus, we can transfer all the initial rotation span responses to a binary response scale.</p>
<pre class="r"><code>dat1 &lt;- key2binary(wmirot[,-1],
    key = c(2,3,4,5,2,3,4,5,2,3,4,5))
head(dat1)</code></pre>
<pre><code>##      S1.2 S1.3 S1.4 S1.5 S2.2 S2.3 S2.4 S2.5 S3.2 S3.3 S3.4 S3.5
## [1,]    1    0    0    0    0    1    0    0    0    0    0    0
## [2,]    1    0    0    0    1    1    0    0    1    0    0    0
## [3,]    1    0    1    0    1    1    1    0    0    0    0    0
## [4,]    1    0    0    0    1    0    0    0    1    0    0    0
## [5,]    1    1    1    1    1    1    1    0    1    1    1    0
## [6,]    1    1    0    0    1    1    1    0    1    0    0    0</code></pre>
<div id="assumption-checks" class="section level2">
<h2>Assumption Checks</h2>
<p>Unidimensional IRT models assume that all items are measuring a single continuous latent variable. There are different ways to test the unidimensionality assumption. For example, we can estimate McDonald’s hierarchical Omega (<span class="math inline">\(\omega_h\)</span>), which conceptually reflects percentage of variance in the scale scores accounted for by a general factor. An arbitrary cutoff of <span class="math inline">\(\omega_h\)</span> &gt; .70 is usually used as the rule of thumb. Unfortunately, the current data violated this assumption using this rule of thumb (<span class="math inline">\(\omega_h\)</span> = .56), but for demonstration purpose, we went along with further analyses.</p>
<p>For further details on unidimensionality, see <a href="https://doi.org/10.1007/BF02289858">Berge &amp; Socan (2004)</a> and <a href="https://doi.org/10.1177/0146621605278814">Zinbarg, Yovel, Revelle, &amp; McDonald (2006)</a>.</p>
<p>Another assumption of IRT is local independence, such that item responses are independent of one another. This assumption can be checked during the modeling fitting process by investigating the residuals and compute local dependence indices using the “residuals” function.</p>
<pre class="r"><code>summary(omega(dat1, plot = F))</code></pre>
<pre><code>## Omega 
## omega(m = dat1, plot = F)
## Alpha:                 0.7 
## G.6:                   0.69 
## Omega Hierarchical:    0.56 
## Omega H asymptotic:    0.77 
## Omega Total            0.73 
## 
## With eigenvalues of:
##    g  F1*  F2*  F3*   h2 
## 1.72 0.23 0.60 0.43 1.03 
## The degrees of freedom for the model is 33  and the fit was  0.07 
## The number of observations was  262  with Chi Square =  17.75  with prob &lt;  0.99 
## 
## The root mean square of the residuals is  0.03 
## The df corrected root mean square of the residuals is  0.04 
## 
## RMSEA and the  0.9 confidence intervals are  0 0 0
## BIC =  -166.01Explained Common Variance of the general factor =  0.58 
## 
##  Total, General and Subset omega for each subset
##                                                  g  F1*  F2*  F3*
## Omega total for total scores and subscales    0.73 0.55 0.48 0.55
## Omega general for total scores and subscales  0.56 0.45 0.13 0.37
## Omega group for total scores and subscales    0.11 0.11 0.35 0.18</code></pre>
</div>
<div id="pl-rasch-model" class="section level2">
<h2>1PL (Rasch) Model</h2>
<p>We can start with a 1PL (Rasch) model, in which the discrimination parameters for all items are fixed to 1, while difficulty paramters are freely estimated in the model.</p>
<pre class="r"><code># Model specification. Here we indicate that all columns in the dataset (1 to 12) measure the same latent factor (&quot;rotation&quot;)
uniDich.model1 &lt;- mirt.model(&quot;rotation = 1 - 12&quot;)

# Model estimation. Here we indicate that we are estimating a Rasch model, and standard errors for parameters are estimated.
uniDich.result1 &lt;- mirt::mirt(dat1, uniDich.model1, itemtype = &quot;Rasch&quot;, SE = TRUE)</code></pre>
<div id="model-and-item-fits" class="section level3">
<h3>Model and Item Fits</h3>
<p>we can now investigate model fit statistics using the “M2” function, which provides the M2 index, the M2-based root mean square error of approximation (RMSEA), the standardized root mean square residual (SRMSR), and comparative fit index (CFI &amp; TLI) to assess adequacy of model fit. A set of arbitrary cutoff values for the fit indices are provided here: RMSEA &lt; .06; SRMSR &lt; .08; CFI &gt; .95; TLI &gt; .95. Models with fit indices that saturate these cutoff values are commonly considered to have good fit. In this example, the non-significant M2 and all fit indices indicated great fit.</p>
<pre class="r"><code>M2(uniDich.result1)</code></pre>
<pre><code>##             M2 df         p RMSEA RMSEA_5   RMSEA_95      SRMSR      TLI CFI
## stats 57.35425 65 0.7388256     0       0 0.02786492 0.05863013 1.016119   1</code></pre>
<p>In IRT analyses, we can also assess how well each item fits the model. This is especially useful for item inspection and scale revision. The “itemfit” function provides S-X2 index as well as RMSEA values to assess the degree of item fit for each item. Non-significant S-X2 values and RMSEA &lt; .06 are usually considered evidence of adequate fit for an item. In the current example, all items seem to fit the model well based on the indices.</p>
<pre class="r"><code>itemfit(uniDich.result1)</code></pre>
<pre><code>##    item   S_X2 df.S_X2 RMSEA.S_X2 p.S_X2
## 1  S1.2  7.250       5      0.042  0.203
## 2  S1.3 11.494       6      0.059  0.074
## 3  S1.4  7.566       6      0.032  0.272
## 4  S1.5  6.330       5      0.032  0.275
## 5  S2.2  4.483       6      0.000  0.612
## 6  S2.3  5.462       6      0.000  0.486
## 7  S2.4  5.275       6      0.000  0.509
## 8  S2.5  3.816       5      0.000  0.576
## 9  S3.2  1.528       6      0.000  0.958
## 10 S3.3  7.055       6      0.026  0.316
## 11 S3.4  5.081       6      0.000  0.533
## 12 S3.5  8.589       5      0.052  0.127</code></pre>
<p>Along with the model and item fits we can also check the local independence assumption using the “residuals” function. The following scripts provide the LD matrix as well as dfs and p-values for all LD indices. Large and significant LD indices are indicators of potential issues of local dependence and may require further attention.</p>
<pre class="r"><code>residuals(uniDich.result1, df.p = T)</code></pre>
<pre><code>## Degrees of freedom (lower triangle) and p-values:
## 
##      S1.2  S1.3  S1.4  S1.5  S2.2  S2.3  S2.4  S2.5  S3.2  S3.3  S3.4  S3.5
## S1.2      0.812 0.572 0.317 0.736 0.537 0.572 0.038 0.228 0.142 0.224 0.302
## S1.3    1       0.441 0.326 0.221 0.176 0.827 0.232 0.553 0.508 0.160 0.778
## S1.4    1 1.000       0.833 0.077 0.643 0.414 0.248 0.694 0.237 0.412 0.482
## S1.5    1 1.000 1.000       0.486 0.734 0.575 0.144 0.600 0.677 0.879 0.553
## S2.2    1 1.000 1.000 1.000       0.741 0.758 0.214 0.233 0.084 0.770 0.214
## S2.3    1 1.000 1.000 1.000 1.000       0.265 0.505 0.261 0.126 0.194 0.222
## S2.4    1 1.000 1.000 1.000 1.000 1.000       0.429 0.694 0.534 0.063 0.248
## S2.5    1 1.000 1.000 1.000 1.000 1.000 1.000       0.523 0.187 0.866 0.086
## S3.2    1 1.000 1.000 1.000 1.000 1.000 1.000 1.000       0.151 0.774 0.872
## S3.3    1 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000       0.352 0.717
## S3.4    1 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000       0.156
## S3.5    1 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000 1.000      
## 
## LD matrix (lower triangle) and standardized residual correlations (upper triangle)
## 
## Upper triangle summary:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  -0.128  -0.043  -0.014   0.000   0.060   0.109 
## 
##       S1.2   S1.3   S1.4   S1.5   S2.2   S2.3   S2.4   S2.5   S3.2   S3.3
## S1.2       -0.015 -0.035  0.062 -0.021 -0.038 -0.035 -0.128  0.074 -0.091
## S1.3 0.057         0.048  0.061  0.076  0.084  0.013  0.074  0.037  0.041
## S1.4 0.319  0.595        -0.013  0.109 -0.029 -0.051 -0.071 -0.024  0.073
## S1.5 1.002  0.966  0.045        -0.043 -0.021 -0.035 -0.090  0.032  0.026
## S2.2 0.114  1.498  3.120  0.486         0.020  0.019  0.077  0.074  0.107
## S2.3 0.382  1.827  0.215  0.115  0.109        -0.069 -0.041  0.069  0.094
## S2.4 0.319  0.048  0.669  0.314  0.095  1.242        -0.049 -0.024 -0.038
## S2.5 4.286  1.428  1.335  2.136  1.547  0.444  0.626         0.039 -0.082
## S3.2 1.453  0.351  0.155  0.274  1.425  1.265  0.155  0.408         0.089
## S3.3 2.158  0.439  1.401  0.174  2.979  2.336  0.387  1.744  2.059       
## S3.4 1.479  1.976  0.673  0.023  0.085  1.684  3.445  0.029  0.082  0.866
## S3.5 1.067  0.080  0.495  0.352  1.547  1.491  1.335  2.953  0.026  0.132
##        S3.4   S3.5
## S1.2 -0.075 -0.064
## S1.3  0.087 -0.017
## S1.4 -0.051  0.043
## S1.5  0.009 -0.037
## S2.2  0.018  0.077
## S2.3  0.080 -0.075
## S2.4 -0.115 -0.071
## S2.5  0.010 -0.106
## S3.2 -0.018 -0.010
## S3.3  0.057 -0.022
## S3.4        -0.088
## S3.5  2.012</code></pre>
<p>Other than the model fits and item fits, the “mirt” package also provides methods for calculating person fit statistics such as Zh statistics using the “personfit” function. In general, person fit statistics indicate how much a person’s responses on this test deviates from the the model prediction. See the “mirt” documentation and <a href="https://doi.org/10.1111/j.2044-8317.1985.tb00817.x">Drasgow, Levine, and Williams (1985)</a> for further details.</p>
<pre class="r"><code>head(personfit(uniDich.result1))</code></pre>
<pre><code>##      outfit    z.outfit     infit     z.infit         Zh
## 1 0.5429718  0.02890866 0.9234628 -0.06855284  0.3245494
## 2 0.3222275 -0.81981695 0.4792737 -1.50551326  1.2108896
## 3 1.3572362  0.68361016 1.6380112  1.45638093 -1.2704872
## 4 0.2944648 -0.60327684 0.4464912 -1.66830681  1.2602444
## 5 0.3693042 -0.15612325 0.6267169 -0.83751757  0.8026636
## 6 0.5580941 -0.53989285 0.8091663 -0.35965405  0.5450324</code></pre>
</div>
<div id="irt-paramters" class="section level3">
<h3>IRT Paramters</h3>
<p>We can obtain the item parameters from the model. As aforementioned, for a Rasch model, all discrimination parameters are fixed to 1, while difficulty parameters are freely estimated. In the output, the second column (“a”) contains the discrimination parameters and the third column (b) contains the difficulty parameters.</p>
<p>In this example, we presented the IRT parameters using the conventional approach, such that a larger <em>b</em> parameter indicates higher difficulty of an item. For example, the second item, S1.3 (item size 3 in the 1st block), has a b = -0.94. This indicates that, according to the model estimation, a person with ability level that is 0.94 standard deviation below the average has 50% of chance to answer this item (S1.3) correctly.</p>
<pre class="r"><code># IRT parameters from the estimated model. For this example, we are obtaining simplified output without SEs/CIs (simplify = TRUE) for conventional IRT parameters (IRTpar = TRUE).
coef(uniDich.result1,simplify = TRUE, IRTpar = TRUE)$items</code></pre>
<pre><code>##      a          b g u
## S1.2 1 -3.0033639 0 1
## S1.3 1 -0.9388653 0 1
## S1.4 1  0.5864289 0 1
## S1.5 1  2.4373369 0 1
## S2.2 1 -2.6395715 0 1
## S2.3 1 -1.4247025 0 1
## S2.4 1  0.5864289 0 1
## S2.5 1  2.3201998 0 1
## S3.2 1 -2.3398444 0 1
## S3.3 1 -0.9845154 0 1
## S3.4 1  0.3420016 0 1
## S3.5 1  2.3201998 0 1</code></pre>
</div>
<div id="visualizing-the-item-and-scale-characteristics" class="section level3">
<h3>Visualizing the Item and Scale Characteristics</h3>
<p>We can visualize corresponding item and scale characteristics from the model by a variety of plot methods in “mirt”. The plots presents how items and the entire scale relate to the latent trait across the scale.<br />
We can start with the item trace plots for the 12 items. The item trace plots visualize the probability of responding “1” to an item as a function of <span class="math inline">\(\theta\)</span>. According to the item trace plot of this example, the 3 items with item size 2 (S1.2,S2.2,S3.2) are relatively easy items, in which subjects with average ability (<span class="math inline">\(\theta\)</span> = 0) are estimated to have about 80% to 90% of chance to answer correctly. On the other hand, the 3 items with size 5 are relatively hard items, in which subjects with average ability are estimated to have about only 10% to 20% of chance to answer correctly.</p>
<pre class="r"><code># In the function we cam specify the range of theta we&#39;d like to visualize on the x axis of the plots. In this example we set it to -4 to 4 (4 SDs below and above average).
plot(uniDich.result1, type = &quot;trace&quot;, theta_lim = c(-4,4))</code></pre>
<p><img src="https://hanhao23.github.io/project/irttutorial/index_files/figure-html/unidich%20Rasch%20ploting1-1.png" width="672" />
Other than the item trace plots, we can also look at the item information plots. Item information plots visualize how much “information” about the latent trait ability an item can provide. Conceptually, higher information implies less error of measure, and the peak of an item information curve is at the point of its b parameter. Thus, for easy items (such as the 3 items in the most left column below), little information are provided on subjects with high ability levels (because they will almost always answer correctly).</p>
<pre class="r"><code># We can specify the exact set of items we want to plot in the ploting function of mirt. Here we can also only visualize the 1st, 5th, and 9th item from the dataset by addin an argument &quot;which.items = c(1,5,9)&quot; in the function. This will make the function to only plot the 3 items with set size 2 in the task. Please feel free to give a try.
plot(uniDich.result1, type = &quot;infotrace&quot;)</code></pre>
<p><img src="https://hanhao23.github.io/project/irttutorial/index_files/figure-html/unidich%20Rasch%20ploting2-1.png" width="672" />
The “itemplot” function can provides more details regarding an item. This is an example that visualize the item trace plot of item 1 with confidence envelope.</p>
<pre class="r"><code>itemplot(uniDich.result1, item = 1, type = &quot;trace&quot;, CE = TRUE)</code></pre>
<p><img src="https://hanhao23.github.io/project/irttutorial/index_files/figure-html/unidich%20Rasch%20ploting3-1.png" width="672" />
Lastly, we can plot the information curve for the entire test. This is based on the sum of all item information curves and indicate how much information a test can provide at different latent trait levels based on the model. As aforementioned, high information indicate less error (low SE) of measurement. An ideal (but impossible) test would have high test information at all levels of latent trait levels.</p>
<pre class="r"><code>plot(uniDich.result1, type = &quot;infoSE&quot;)</code></pre>
<p><img src="https://hanhao23.github.io/project/irttutorial/index_files/figure-html/unidich%20Rasch%20ploting4-1.png" width="672" /></p>
</div>
</div>
<div id="pl-model" class="section level2">
<h2>2PL Model</h2>
<p>We can also estimate a 2PL model on the same binary data of rotation span task. In a 2PL model, not only the item difficulty parameters (<em>b</em>s) but also the item discrimination parameters (<em>a</em>s) are estimated. Thus, a 2PL model assumes that different items vary in the ability to discriminate between persons with different latent trait levels.</p>
<pre class="r"><code>uniDich.model2 &lt;- mirt.model(&quot;rotation = 1 - 12&quot;)

uniDich.result2 &lt;- mirt::mirt(dat1, uniDich.model2, itemtype = &quot;2PL&quot;, SE = TRUE)</code></pre>
<div id="model-and-item-fits-1" class="section level3">
<h3>Model and Item Fits</h3>
<p>Similarly, we can obtain corresponding statistics of the model such as model fit and item fit statistics. In this example, the overall model fit for the 2PL model is good.</p>
<pre class="r"><code>M2(uniDich.result2)</code></pre>
<pre><code>##             M2 df         p RMSEA RMSEA_5   RMSEA_95      SRMSR      TLI CFI
## stats 40.90802 54 0.9054692     0       0 0.01662836 0.04004632 1.033223   1</code></pre>
<p>Item fit statistics for this 2PL model indicate that the 2nd item (S1.3) may need further attention (significant S-X2 and large RMSEA).</p>
<pre class="r"><code>itemfit(uniDich.result2)</code></pre>
<pre><code>##    item   S_X2 df.S_X2 RMSEA.S_X2 p.S_X2
## 1  S1.2  1.607       6      0.000  0.952
## 2  S1.3 10.427       4      0.078  0.034
## 3  S1.4  6.922       5      0.038  0.227
## 4  S1.5  5.373       5      0.017  0.372
## 5  S2.2  4.646       5      0.000  0.461
## 6  S2.3  2.783       5      0.000  0.733
## 7  S2.4  3.550       6      0.000  0.737
## 8  S2.5  3.390       5      0.000  0.640
## 9  S3.2  1.839       5      0.000  0.871
## 10 S3.3  7.201       6      0.028  0.303
## 11 S3.4  6.146       6      0.010  0.407
## 12 S3.5  7.840       5      0.047  0.165</code></pre>
</div>
<div id="irt-parameters" class="section level3">
<h3>IRT Parameters</h3>
<p>We can obtain the item parameters from the model. For a 2PL model, both the item discrimination parameters and the item difficulty parameters are freely estimated. Similar to the output of the Rasch model, the second column (“a”) contains the discrimination parameters and the third column (b) contains the difficulty parameters. We can see that, unlike the Rasch model, now every item has a unique discrimination parameter.</p>
<p>For a dichotomous 2PL model, the item discrimination parameters reflect how well an item could discriminate between persons with low and high ability/trait levels. Furthermore, the <em>a</em> parameter also reflects the magnitude to which an item is related to the latent trait measured by the scale. Thus, a low discrimination parameter usually indicates potential issues for an item comparing to the general scale.</p>
<pre class="r"><code>coef(uniDich.result2,simplify = TRUE, IRTpar = TRUE)$items</code></pre>
<pre><code>##              a          b g u
## S1.2 0.8196465 -3.2455844 0 1
## S1.3 1.7771645 -0.6171063 0 1
## S1.4 1.3365861  0.4431670 0 1
## S1.5 1.2963837  1.9023919 0 1
## S2.2 1.7058414 -1.7589910 0 1
## S2.3 1.3696765 -1.0753956 0 1
## S2.4 0.8589407  0.5905375 0 1
## S2.5 0.9387174  2.2626112 0 1
## S3.2 1.4477736 -1.7033180 0 1
## S3.3 1.5741235 -0.6888211 0 1
## S3.4 1.2459076  0.2655880 0 1
## S3.5 0.9445384  2.2521152 0 1</code></pre>
</div>
<div id="visualizing-the-item-and-scale-plots" class="section level3">
<h3>Visualizing the Item and Scale Plots</h3>
<p>Comparing to the Rasch model, the estimated <em>a</em> parameters in a 2PL model are also reflected in item trace plots, such that the differences in <em>a</em>s are reflected by the changes in the steepness of the item trace curves. Higher <em>a</em>s would be reflected as steeper item trace curves.</p>
<pre class="r"><code>plot(uniDich.result2, type = &quot;trace&quot;, theta_lim = c(-4,4))</code></pre>
<p><img src="https://hanhao23.github.io/project/irttutorial/index_files/figure-html/unidich%202PL%20ploting1-1.png" width="672" /></p>
<p>The freely estimated discrimination parameters are also reflected in the item information plots. As we can see, comparing to the Rasch model, the peaks of information curves are varying across items in the 2PL model.</p>
<pre class="r"><code>plot(uniDich.result2, type = &quot;infotrace&quot;)</code></pre>
<p><img src="https://hanhao23.github.io/project/irttutorial/index_files/figure-html/unidich%202PL%20ploting2-1.png" width="672" /></p>
</div>
</div>
<div id="model-specifications" class="section level2">
<h2>Model Specifications</h2>
<p>The model specification function of “mirt” provides arguments for further constraints in an IRT model and can be used for testing specific assumptions regarding the item characteristics.<br />
For example, in the rotation span task, items with the exact same set size are designed in the exact same way. Thus, we consider the items with the same set size equivalent in their ability to discriminate persons with different ability levels. To estimate this model, we can specify the constraints in the model specification function. As is presented, in the function we specify an equal <em>a</em> parameter for items 1, 5, &amp; 9, which are labeled “S1.2”, “S2.2”, and “S3.2” in the dataset (these are the 3 items with set size 2); another equal <em>a</em> for items 2, 6, &amp; 1; another for items 3, 7, and 11; and another for items 4, 8, and 12.</p>
<pre class="r"><code>uniDich.model3 &lt;- mirt.model(&quot;rotation = 1 - 12
                             CONSTRAIN = (1,5,9,a1), (2,6,10,a1),(3,7,11,a1),(4,8,12,a1)&quot;)

uniDich.result3 &lt;- mirt::mirt(dat1, uniDich.model3, itemtype = &quot;2PL&quot;, SE = TRUE)</code></pre>
<p>The specification in constraints is reflected in the IRT parameters from this model. As we can observe, in the IRT parameters output, items with the same set sizes are estimated to have the exact same <em>a</em> parameters. For all items with size 2, <em>a</em> = 1.31, and for all items with size 3, <em>a</em> = 1.55, etc. On the other hand, the <em>b</em> parameters are still freely estimated regardless of the item size.</p>
<pre class="r"><code>coef(uniDich.result3,simplify = TRUE, IRTpar = TRUE)$items</code></pre>
<pre><code>##             a          b g u
## S1.2 1.314847 -2.3120591 0 1
## S1.3 1.551951 -0.6626354 0 1
## S1.4 1.127870  0.4902232 0 1
## S1.5 1.036344  2.2120724 0 1
## S2.2 1.314847 -2.0337955 0 1
## S2.3 1.551951 -1.0029799 0 1
## S2.4 1.127870  0.4902232 0 1
## S2.5 1.036344  2.1036240 0 1
## S3.2 1.314847 -1.8044209 0 1
## S3.3 1.551951 -0.6946542 0 1
## S3.4 1.127870  0.2815835 0 1
## S3.5 1.036344  2.1036240 0 1</code></pre>
<p>We can also do model comparisons for nested models with different constraints. For example, we can test the difference between this constrained model and the previous 2PL model without any constraints on discrimination. This is similar to a model comparison based on chi-squared statistics for nested SEM models. As we can see, results indicate that the two models are not significantly different from each other, <span class="math inline">\(\Delta\chi^2\)</span>(8) = 8.68, <em>p</em> = .37.</p>
<pre class="r"><code>anova(uniDich.result2,uniDich.result3)</code></pre>
<pre><code>##                      AIC    SABIC       HQ      BIC    logLik     X2 df   p
## uniDich.result2 2948.644 2958.194 2983.065 3034.285 -1450.322              
## uniDich.result3 2941.329 2947.695 2964.276 2998.422 -1454.664 -8.684 -8 NaN</code></pre>
</div>
</div>
<div id="unidimensional-polytomous-irt-model" class="section level1">
<h1>Unidimensional Polytomous IRT Model</h1>
<p>In the previous section we have conducted dichotomous IRT analyses on the rotation span task dataset with binary responses. However, the initial rotation span dataset consist of numbers of correctly recalled elements for each item. In other words, each item actually has more than two possible response categories that are at least ordinal. For example, for an item with set size 2 (2 elements in the item), there are 3 possible response outcomes: 0, 1, and 2. Thus, we could fit and assess a polytomous IRT model to this type of measures, such as partial-scored tests and Likert-type surveys.</p>
<pre class="r"><code>dat2 &lt;- as.matrix(wmirot[,-1])
head(dat2)</code></pre>
<pre><code>##      S1.2 S1.3 S1.4 S1.5 S2.2 S2.3 S2.4 S2.5 S3.2 S3.3 S3.4 S3.5
## [1,]    2    1    0    0    0    3    1    0    1    1    0    0
## [2,]    2    2    1    1    2    3    2    2    2    2    1    1
## [3,]    2    1    4    1    2    3    4    1    1    2    0    3
## [4,]    2    2    3    1    2    0    1    1    2    2    3    4
## [5,]    2    3    4    5    2    3    4    4    2    3    4    2
## [6,]    2    3    0    2    2    3    4    3    2    1    2    1</code></pre>
<div id="generalized-partial-credit-model" class="section level2">
<h2>Generalized Partial Credit Model</h2>
<p>In this section, we will apply the generalized partial credit model (GPCM; <a href="https://doi.org/10.1002/j.2333-8504.1992.tb01436.x">Muraki, 1992</a>) to the rotation span data. As a polytomous model, GPCM estimates one item threshold parameter for <strong>each response category</strong> in an item instead of one difficulty parameter for an item. Further more, GPCM assumes an unique item discrimination parameter for each item instead of assuming a unitary reliability across items (like the Rasch model).</p>
<pre class="r"><code>unipoly.model1 &lt;- mirt.model(&quot;rotation = 1 - 12&quot;)

unipoly.result1 &lt;- mirt::mirt(dat2, uniDich.model2, itemtype = &quot;gpcm&quot;, SE = TRUE)</code></pre>
<div id="model-and-item-fits-2" class="section level3">
<h3>Model and Item Fits</h3>
<p>Similarly, we can obtain corresponding statistics of the model such as model fit and item fit statistics. In this example, the overall model fit and all item fits for the GPCM model are good.</p>
<pre class="r"><code>M2(unipoly.result1)</code></pre>
<pre><code>##             M2 df         p RMSEA RMSEA_5   RMSEA_95      SRMSR      TLI CFI
## stats 23.66605 24 0.4808204     0       0 0.04927329 0.04771738 1.005053   1</code></pre>
<pre class="r"><code>itemfit(unipoly.result1)</code></pre>
<pre><code>##    item   S_X2 df.S_X2 RMSEA.S_X2 p.S_X2
## 1  S1.2 15.329      11      0.039  0.168
## 2  S1.3 46.224      32      0.041  0.050
## 3  S1.4 43.506      48      0.000  0.657
## 4  S1.5 44.058      58      0.000  0.912
## 5  S2.2 20.725      13      0.048  0.079
## 6  S2.3 30.299      26      0.025  0.255
## 7  S2.4 48.715      50      0.000  0.525
## 8  S2.5 71.664      61      0.026  0.165
## 9  S3.2 13.519      17      0.000  0.701
## 10 S3.3 20.588      32      0.000  0.940
## 11 S3.4 52.075      51      0.009  0.432
## 12 S3.5 63.890      63      0.007  0.445</code></pre>
</div>
<div id="irt-parameters-1" class="section level3">
<h3>IRT Parameters</h3>
<p>For a GPCM model, the item discrimination parameters and the item threshold parameters are freely estimated. In a GPCM model, the item threshold parameter is defined as the trait level in which one has an equal probability of choosing the <em>k</em>th response category over the <em>k-1</em>th category in an item. When choosing between the <em>k</em>th and the <em>k-1</em>th category, subjects with trait levels higher than that threshold are more likely to approach the <em>k</em>th, while subjects with trait levels lower than that threshold are more likely to approach the <em>k-1</em>th.</p>
<pre class="r"><code>coef(unipoly.result1,simplify = TRUE, IRTpars = TRUE)$items</code></pre>
<pre><code>##              a         b1          b2         b3        b4          b5
## S1.2 0.6354780 -2.4238753 -4.50115962         NA        NA          NA
## S1.3 0.8367055 -1.5716066 -0.89123631 -1.8001978        NA          NA
## S1.4 0.5989767 -1.8187952 -0.50303114  0.5399410 -1.379714          NA
## S1.5 0.4660780 -0.7725926 -0.02659485  0.5368132  1.745108  0.07050096
## S2.2 1.0176875 -1.8131900 -2.77011850         NA        NA          NA
## S2.3 0.8606748 -2.3689773 -0.88851301 -2.2413670        NA          NA
## S2.4 0.4985639 -1.6434258 -0.70470153 -0.3802990 -1.060266          NA
## S2.5 0.4158617 -0.5284300 -1.00120923  1.5317726  1.243526 -0.09643630
## S3.2 0.8508984 -1.3638275 -3.01408652         NA        NA          NA
## S3.3 0.8038394 -1.7838070 -1.03577722 -1.8430426        NA          NA
## S3.4 0.5793661 -0.6192944 -0.94635296  0.0811653 -1.540936          NA
## S3.5 0.4046533 -0.5014941 -0.68390425  0.3561937  1.278277  0.42457494</code></pre>
<p>In this example, the function utilizes the conventional IRT parameterization. In the conventional parameterization, for an item of size <em>p</em>, GPCM estimates <em>p</em> item threshold parameters for each of the categories (from “<em>b_1</em>” for partial scores of 0 and 1 to “<em>b_p</em>” for partial scores p-1 and p), and 1 item discrimination parameter for the item. The second column (“<em>a_1</em>”) contains the discrimination parameters and the later columns (“<em>b_1</em>” to “<em>b_5</em>”) contain all the threshold parameters.</p>
</div>
<div id="visualizing-the-item-and-scale-plots-1" class="section level3">
<h3>Visualizing the Item and Scale Plots</h3>
<p>Similar to the dichotomous 2PL model, the estimated <em>a</em> parameters in a GPCM model are reflected in item trace plots, such that the differences in <em>a</em>s are reflected by the changes in the steepness of the item trace curves. Higher <em>a</em>s would be reflected as steeper item trace curves. On the other hand, the estimated <em>b</em> parameters in a GPCM model are reflected as (x-axis values for) the adjacent points between trace curves for different categories. For example, for Item S3.2, the current GPCM model estimated two threshold parameters: b1 = -1.36 (the adjacent point between curve P1 and P2) and b2 = -3.01 (the adjacent point between curve P2 and P3).</p>
<pre class="r"><code>plot(unipoly.result1, type = &quot;trace&quot;, theta_lim = c(-4,4))</code></pre>
<p><img src="https://hanhao23.github.io/project/irttutorial/index_files/figure-html/unipoly%202PL%20ploting1-1.png" width="672" /></p>
<p>Similar to the dichotomous 2PL model, the freely estimated discrimination parameters are also reflected in the item information plots.</p>
<pre class="r"><code>plot(unipoly.result1, type = &quot;infotrace&quot;)</code></pre>
<p><img src="https://hanhao23.github.io/project/irttutorial/index_files/figure-html/unipoly%202PL%20ploting2-1.png" width="672" /></p>
</div>
<div id="individual-scoring" class="section level3">
<h3>Individual Scoring</h3>
<p>Based on an estimated model, we can also estimate the individual latent trait scores. Conceptually, the estimated latent trait scores are similar to factor scores estimated in CFAs.</p>
<pre class="r"><code>est.theta &lt;- as.data.frame(fscores(unipoly.result1))
head(est.theta)</code></pre>
<pre><code>##     rotation
## 1 -1.9429664
## 2 -0.7051405
## 3 -0.5498356
## 4 -0.6928339
## 5  1.4039574
## 6 -0.3787596</code></pre>
<pre class="r"><code>est.theta %&gt;% 
  ggplot(aes(x=rotation)) +
    geom_histogram(aes(y=..density..),
                   binwidth=.1,
                   colour=&quot;black&quot;, fill=&quot;white&quot;) +
    geom_density(alpha=.2, fill=&quot;aquamarine2&quot;)</code></pre>
<pre><code>## Warning: The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.
## ℹ Please use `after_stat(density)` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<p><img src="https://hanhao23.github.io/project/irttutorial/index_files/figure-html/unipoly%202PL%20scoring-1.png" width="672" /></p>
</div>
</div>
</div>

    </div>

    






<div class="article-tags">
  
  <a class="badge badge-light" href="/tag/item-response-theory/">Item Response Theory</a>
  
  <a class="badge badge-light" href="/tag/working-memory/">Working Memory</a>
  
  <a class="badge badge-light" href="/tag/r/python/">R/Python</a>
  
  <a class="badge badge-light" href="/tag/psychometrics/">Psychometrics</a>
  
  <a class="badge badge-light" href="/tag/academic/">Academic</a>
  
  <a class="badge badge-light" href="/tag/stats/">Stats</a>
  
</div>



<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=https://hanhao23.github.io/project/irttutorial/&amp;text=Intro%20to%20Item%20Response%20Modeling%20in%20R" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=https://hanhao23.github.io/project/irttutorial/&amp;t=Intro%20to%20Item%20Response%20Modeling%20in%20R" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Intro%20to%20Item%20Response%20Modeling%20in%20R&amp;body=https://hanhao23.github.io/project/irttutorial/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=https://hanhao23.github.io/project/irttutorial/&amp;title=Intro%20to%20Item%20Response%20Modeling%20in%20R" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="whatsapp://send?text=Intro%20to%20Item%20Response%20Modeling%20in%20R%20https://hanhao23.github.io/project/irttutorial/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=https://hanhao23.github.io/project/irttutorial/&amp;title=Intro%20to%20Item%20Response%20Modeling%20in%20R" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>












  
  





  
    
    
    
      
    
    
    
    <div class="media author-card content-widget-hr">
      
        
        <img class="avatar mr-3 avatar-circle" src="/author/han-hao/avatar_hu0defa3a20122c19c21248656cc8d680b_330067_270x270_fill_q90_lanczos_center.jpg" alt="Han Hao">
      

      <div class="media-body">
        <h5 class="card-title"><a href="https://hanhao23.github.io/">Han Hao</a></h5>
        <h6 class="card-subtitle">Assistant Professor</h6>
        <p class="card-text">Working memory, attention, intelligence, psychometrics, and R programming.</p>
        <ul class="network-icon" aria-hidden="true">
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="/#contact" >
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://twitter.com/HanHao23" target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
  
    
    
    
    
    
    
    
      
    
    <li>
      <a href="https://scholar.google.com/citations?user=FT_5FJoAAAAJ" target="_blank" rel="noopener">
        <i class="ai ai-google-scholar"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://github.com/hanhao23" target="_blank" rel="noopener">
        <i class="fab fa-github"></i>
      </a>
    </li>
  
</ul>

      </div>
    </div>
  














  
  
  <div class="article-widget content-widget-hr">
    <h3>Related</h3>
    <ul>
      
      <li><a href="/project/glmm/">Intro to Generalized Mixed Effects Model in R</a></li>
      
      <li><a href="/talk/2025psychonomics/">Trial by &#34;Trial&#34;</a></li>
      
      <li><a href="/project/psyc5316/">PSYC 5316 Advanced Quant Methods Materials</a></li>
      
      <li><a href="/publication/uniirt/">An item response theory approach to the measurement of working memory capacit Theory</a></li>
      
      <li><a href="/talk/2024psychonomics/">The Domain-Generality of Working Memory and Fluid Intelligence</a></li>
      
    </ul>
  </div>
  





    <div class="project-related-pages content-widget-hr">
      
      

      
      
      

      
      
      
        <h2>Publications</h2>
        
          
            








  
  





  


<div class="media stream-item">
  <div class="media-body">

    <h3 class="article-title mb-0 mt-0">
      <a href="/publication/uniirt/" >An item response theory approach to the measurement of working memory capacit Theory</a>
    </h3>

    
    <a href="/publication/uniirt/" class="summary-link">
      <div class="article-style">
        This study fitted and compared item response models of item-level responses of different complex span tasks. Results, especially item parameters, may reveal the variety of domain specificity in different complex span tasks.
      </div>
    </a>
    

    <div class="stream-meta article-metadata">

      

      
      <div>
        

  
  <span >Ester Navarro</span>, <span >Kevin Rosales</span>, <span >Han Hao</span>, <span >Andrew R. A. Conway</span>
      </div>
      
    </div>

    
    <div class="btn-links">
      








  






  
  
    
  
<a class="btn btn-outline-primary my-1 mr-1 btn-sm" href="https://osf.io/bhw87/" target="_blank" rel="noopener">
  Code
</a>




  
  <a class="btn btn-outline-primary my-1 mr-1 btn-sm" href="/project/irttutorial/">
    Project
  </a>
  









<a class="btn btn-outline-primary my-1 mr-1 btn-sm" href="https://doi.org/https://doi.org/10.3758/s13428-023-02115-3" target="_blank" rel="noopener">
  DOI
</a>



    </div>
    

  </div>
  <div class="ml-3">
    
    
    
    <a href="/publication/uniirt/" >
      <img src="/publication/uniirt/featured_hub8c4dc1be5af250ccb37187348107fcc_14855_150x0_resize_lanczos_3.png" alt="An item response theory approach to the measurement of working memory capacit Theory">
    </a>
    
  </div>
</div>

          
        
          
            








  
  





  


<div class="media stream-item">
  <div class="media-body">

    <h3 class="article-title mb-0 mt-0">
      <a href="/publication/potsimulation/" >General Intelligence Explained (Away)</a>
    </h3>

    
    <a href="/publication/potsimulation/" class="summary-link">
      <div class="article-style">
        Confirmatory latent factor models on simulated data indicate that a higher-order g can emergy even without a common cause.
      </div>
    </a>
    

    <div class="stream-meta article-metadata">

      

      
      <div>
        

  
  <span >Andrew R. A. Conway</span>, <span >Kristof Kovacs</span>, <span ><a href="/author/han-hao/">Han Hao</a></span>, <span >Jean-paul Snijder</span>
      </div>
      
    </div>

    
    <div class="btn-links">
      








  









  
    
  

  
  <a class="btn btn-outline-primary my-1 mr-1 btn-sm" href="/project/irttutorial/">
    Project
  </a>
  

  
    
  










  
  
  
    
  
  
  
  
  
    
  
  <a class="btn btn-outline-primary my-1 mr-1 btn-sm" href="https://osf.io/kwczm/" target="_blank" rel="noopener">
    
    OSF
  </a>


    </div>
    

  </div>
  <div class="ml-3">
    
    
    
    <a href="/publication/potsimulation/" >
      <img src="/publication/potsimulation/featured_hubac08dcc72a69c8311c7dc079fc7f88a_124005_150x0_resize_lanczos_3.png" alt="General Intelligence Explained (Away)">
    </a>
    
  </div>
</div>

          
        
      

      
      
      
        <h2>Talks</h2>
        
          
            








  
  





  


<div class="media stream-item">
  <div class="media-body">

    <h3 class="article-title mb-0 mt-0">
      <a href="/talk/2023isir/" >Simulating the Process Overlap Theory of Intelligence - A Unified Framework Bridging Psychometric and Cognitive Perspectives</a>
    </h3>

    
    <a href="/talk/2023isir/" class="summary-link">
      <div class="article-style">
        Poster in 2023 Annual ISIR Conference
      </div>
    </a>
    

    <div class="stream-meta article-metadata">

      
      <div>
        <span>
          Jul 20, 2023 12:00 AM
        </span>
        
      </div>
      

      
      <div>
        

  
  <span ><a href="/author/han-hao/">Han Hao</a></span>, <span >Andrew R. A. Conway</span>, <span >Kristof Kovacs</span>, <span >Jean-Paul Snijder</span>
      </div>
      
    </div>

    
    <div class="btn-links">
      








  









  
    
  

  
  <a class="btn btn-outline-primary my-1 mr-1 btn-sm" href="/project/irttutorial/">
    Project
  </a>
  

  
    
  











    </div>
    

  </div>
  <div class="ml-3">
    
    
    
    <a href="/talk/2023isir/" >
      <img src="/talk/2023isir/featured_hu397eeb0a19f258bba0596aadda386df0_2471305_150x0_resize_lanczos_3.png" alt="Simulating the Process Overlap Theory of Intelligence - A Unified Framework Bridging Psychometric and Cognitive Perspectives">
    </a>
    
  </div>
</div>

          
        
      
    </div>
  </div>
</article>

      

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha256-yt2kYMy0w8AbtF89WXb2P1rfjcP/HTHLT7097U8Y5b8=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js" integrity="sha256-eOgo0OtLL4cdq7RdwRUiGKLX9XsIJ7nGhWEKbohmVAQ=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/languages/r.min.js"></script>
        
      

    

    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.5.1/leaflet.js" integrity="sha256-EErZamuLefUnbMBQbsEqu1USa+btR2oIlCpBJbyD4/g=" crossorigin="anonymous"></script>
    

    
    
    <script>const code_highlighting = true;</script>
    

    
    
    <script>const isSiteThemeDark = false;</script>
    

    
    
    
    
    
    
    <script>
      const search_config = {"indexURI":"/index.json","minLength":1,"threshold":0.3};
      const i18n = {"no_results":"No results found","placeholder":"Search...","results":"results found"};
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks",
        'slides' : "Slides"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.72756512af279b10e3e4b09540ed6e9f.js"></script>

    






  
  
  <div class="container">
    <footer class="site-footer">
  

  <p class="powered-by">
    hanhao23 © 2026
  </p>

  
  






  <p class="powered-by">
    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" class="back-to-top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
